/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FundsManagerInterface extends ethers.utils.Interface {
  functions: {
    "claimDeposit(bytes)": FunctionFragment;
    "fundsManagerETH()": FunctionFragment;
    "isTransactionClaimed(bytes32)": FunctionFragment;
    "reversePlasma()": FunctionFragment;
    "setInitialValues(address,address,address)": FunctionFragment;
    "tokenOnETH()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimDeposit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundsManagerETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTransactionClaimed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reversePlasma",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialValues",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOnETH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claimDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundsManagerETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransactionClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reversePlasma",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenOnETH", data: BytesLike): Result;

  events: {};
}

export class FundsManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FundsManagerInterface;

  functions: {
    /**
     * Allows to submit a proof for a transaction done on ETH.
     * @param _rawProof : RLP(ethBlockNumber, txIndex, rawTx, tx MPP, rawReceipt, receipt MPP).
     */
    claimDeposit(
      _rawProof: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fundsManagerETH(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    /**
     * Gets whether an deposit transaction hash (on ETH) is already claimed for getting native tokens.
     * @param _transactionHash : Hash of the transaction.
     */
    isTransactionClaimed(
      _transactionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    reversePlasma(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    /**
     * Sets initial enviornment values.
     * @param _fundsManagerETH : Address of Funds Manager contract on ETH.
     * @param _reversePlasma : Address of Reverse Plasma contract on ESN.
     * @param _tokenOnETH : Address of Era Swap ERC20 contract on ETH.
     */
    setInitialValues(
      _reversePlasma: string,
      _tokenOnETH: string,
      _fundsManagerETH: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    tokenOnETH(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  /**
   * Allows to submit a proof for a transaction done on ETH.
   * @param _rawProof : RLP(ethBlockNumber, txIndex, rawTx, tx MPP, rawReceipt, receipt MPP).
   */
  claimDeposit(
    _rawProof: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fundsManagerETH(overrides?: CallOverrides): Promise<string>;

  /**
   * Gets whether an deposit transaction hash (on ETH) is already claimed for getting native tokens.
   * @param _transactionHash : Hash of the transaction.
   */
  isTransactionClaimed(
    _transactionHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  reversePlasma(overrides?: CallOverrides): Promise<string>;

  /**
   * Sets initial enviornment values.
   * @param _fundsManagerETH : Address of Funds Manager contract on ETH.
   * @param _reversePlasma : Address of Reverse Plasma contract on ESN.
   * @param _tokenOnETH : Address of Era Swap ERC20 contract on ETH.
   */
  setInitialValues(
    _reversePlasma: string,
    _tokenOnETH: string,
    _fundsManagerETH: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  tokenOnETH(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    /**
     * Allows to submit a proof for a transaction done on ETH.
     * @param _rawProof : RLP(ethBlockNumber, txIndex, rawTx, tx MPP, rawReceipt, receipt MPP).
     */
    claimDeposit(
      _rawProof: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    fundsManagerETH(overrides?: CallOverrides): Promise<string>;

    /**
     * Gets whether an deposit transaction hash (on ETH) is already claimed for getting native tokens.
     * @param _transactionHash : Hash of the transaction.
     */
    isTransactionClaimed(
      _transactionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    reversePlasma(overrides?: CallOverrides): Promise<string>;

    /**
     * Sets initial enviornment values.
     * @param _fundsManagerETH : Address of Funds Manager contract on ETH.
     * @param _reversePlasma : Address of Reverse Plasma contract on ESN.
     * @param _tokenOnETH : Address of Era Swap ERC20 contract on ETH.
     */
    setInitialValues(
      _reversePlasma: string,
      _tokenOnETH: string,
      _fundsManagerETH: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenOnETH(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    /**
     * Allows to submit a proof for a transaction done on ETH.
     * @param _rawProof : RLP(ethBlockNumber, txIndex, rawTx, tx MPP, rawReceipt, receipt MPP).
     */
    claimDeposit(
      _rawProof: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    fundsManagerETH(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets whether an deposit transaction hash (on ETH) is already claimed for getting native tokens.
     * @param _transactionHash : Hash of the transaction.
     */
    isTransactionClaimed(
      _transactionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reversePlasma(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Sets initial enviornment values.
     * @param _fundsManagerETH : Address of Funds Manager contract on ETH.
     * @param _reversePlasma : Address of Reverse Plasma contract on ESN.
     * @param _tokenOnETH : Address of Era Swap ERC20 contract on ETH.
     */
    setInitialValues(
      _reversePlasma: string,
      _tokenOnETH: string,
      _fundsManagerETH: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    tokenOnETH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Allows to submit a proof for a transaction done on ETH.
     * @param _rawProof : RLP(ethBlockNumber, txIndex, rawTx, tx MPP, rawReceipt, receipt MPP).
     */
    claimDeposit(
      _rawProof: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fundsManagerETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets whether an deposit transaction hash (on ETH) is already claimed for getting native tokens.
     * @param _transactionHash : Hash of the transaction.
     */
    isTransactionClaimed(
      _transactionHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reversePlasma(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Sets initial enviornment values.
     * @param _fundsManagerETH : Address of Funds Manager contract on ETH.
     * @param _reversePlasma : Address of Reverse Plasma contract on ESN.
     * @param _tokenOnETH : Address of Era Swap ERC20 contract on ETH.
     */
    setInitialValues(
      _reversePlasma: string,
      _tokenOnETH: string,
      _fundsManagerETH: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    tokenOnETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
