/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { IRegistryDependent } from "./IRegistryDependent";

export class IRegistryDependentFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegistryDependent {
    return new Contract(address, _abi, signerOrProvider) as IRegistryDependent;
  }
}

const _abi = [
  {
    inputs: [],
    name: "kycDapp",
    outputs: [
      {
        internalType: "contract IKycDapp",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_kycDapp",
        type: "address"
      }
    ],
    name: "setKycDapp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
