/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PetPrepaidFundsBucketInterface extends ethers.utils.Interface {
  functions: {
    "addFunds()": FunctionFragment;
    "deployer()": FunctionFragment;
    "petContract()": FunctionFragment;
    "token()": FunctionFragment;
    "withdrawFunds(bool,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addFunds", values?: undefined): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "petContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [boolean, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "petContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;

  events: {
    "FundsDeposited(address,uint256)": EventFragment;
    "FundsWithdrawn(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundsDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsWithdrawn"): EventFragment;
}

export class PetPrepaidFundsBucket extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PetPrepaidFundsBucketInterface;

  functions: {
    /**
     * ERC20 approve is required to be done for this contract earlier
     * this function is used by well wishers to add funds to the fund bucket of PET
     */
    addFunds(overrides?: PayableOverrides): Promise<ContractTransaction>;

    /**
     * address of the maintainer
     */
    deployer(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    /**
     * address of PET Smart Contract
     */
    petContract(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    /**
     * address of Era Swap ERC20 Smart Contract
     */
    token(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    /**
     * this function makes it possible for deployer to withdraw unallocated ES
     */
    withdrawFunds(
      _withdrawEverything: boolean,
      _withdrawlAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  /**
   * ERC20 approve is required to be done for this contract earlier
   * this function is used by well wishers to add funds to the fund bucket of PET
   */
  addFunds(overrides?: PayableOverrides): Promise<ContractTransaction>;

  /**
   * address of the maintainer
   */
  deployer(overrides?: CallOverrides): Promise<string>;

  /**
   * address of PET Smart Contract
   */
  petContract(overrides?: CallOverrides): Promise<string>;

  /**
   * address of Era Swap ERC20 Smart Contract
   */
  token(overrides?: CallOverrides): Promise<string>;

  /**
   * this function makes it possible for deployer to withdraw unallocated ES
   */
  withdrawFunds(
    _withdrawEverything: boolean,
    _withdrawlAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * ERC20 approve is required to be done for this contract earlier
     * this function is used by well wishers to add funds to the fund bucket of PET
     */
    addFunds(overrides?: CallOverrides): Promise<void>;

    /**
     * address of the maintainer
     */
    deployer(overrides?: CallOverrides): Promise<string>;

    /**
     * address of PET Smart Contract
     */
    petContract(overrides?: CallOverrides): Promise<string>;

    /**
     * address of Era Swap ERC20 Smart Contract
     */
    token(overrides?: CallOverrides): Promise<string>;

    /**
     * this function makes it possible for deployer to withdraw unallocated ES
     */
    withdrawFunds(
      _withdrawEverything: boolean,
      _withdrawlAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    FundsDeposited(_depositer: null, _depositAmount: null): EventFilter;

    FundsWithdrawn(_withdrawer: null, _withdrawAmount: null): EventFilter;
  };

  estimateGas: {
    /**
     * ERC20 approve is required to be done for this contract earlier
     * this function is used by well wishers to add funds to the fund bucket of PET
     */
    addFunds(overrides?: PayableOverrides): Promise<BigNumber>;

    /**
     * address of the maintainer
     */
    deployer(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * address of PET Smart Contract
     */
    petContract(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * address of Era Swap ERC20 Smart Contract
     */
    token(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * this function makes it possible for deployer to withdraw unallocated ES
     */
    withdrawFunds(
      _withdrawEverything: boolean,
      _withdrawlAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * ERC20 approve is required to be done for this contract earlier
     * this function is used by well wishers to add funds to the fund bucket of PET
     */
    addFunds(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    /**
     * address of the maintainer
     */
    deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * address of PET Smart Contract
     */
    petContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * address of Era Swap ERC20 Smart Contract
     */
    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * this function makes it possible for deployer to withdraw unallocated ES
     */
    withdrawFunds(
      _withdrawEverything: boolean,
      _withdrawlAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
