/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { PrepaidEsReceiver } from "./PrepaidEsReceiver";

export class PrepaidEsReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PrepaidEsReceiver {
    return new Contract(address, _abi, signerOrProvider) as PrepaidEsReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    name: "prepaidFallback",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
