version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              name: "Update Node.js and npm"
              command: |
                curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
                curl https://www.npmjs.com/install.sh | sudo bash
            - run:
              name: Check current version of node
              command: node -v
            - run: npm install
            - run: npm run build
            - run: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test
